In [7]:
import pandas as pd
import math

In [41]:
pd.set_option("display.max_rows", None)
positions = ["QB", "RB", "TE", "WR"]
adp = pd.read_csv('ADP.csv')

for position in positions:

    df = pd.read_csv(f'{position}_weekly_stats.csv')
    df["Average"] = df.filter(like="FPTS_WK").mean(axis=1)
    df["StdDev"] = df.filter(like="FPTS_WK").std(axis=1)
    df["ProxySharpe"] = (df["Average"] * 17) / (df["StdDev"] * math.sqrt(17))
    df = df.dropna()
    df = df.merge(adp, on="NAME", how="inner")
    globals()[position.lower()] = df

In [42]:
qb.sort_values(by="ProxySharpe", ascending=False)

,NAME,FPTS_WK1,FPTS_WK2,FPTS_WK3,FPTS_WK4,FPTS_WK5,FPTS_WK6,FPTS_WK7,FPTS_WK8,FPTS_WK9,...,FPTS_WK14,FPTS_WK15,FPTS_WK16,FPTS_WK17,FPTS_WK18,TEAM,Average,StdDev,ProxySharpe,ADP
12,Drake Maye,15.8,26.3,19.2,23.2,12.1,27.2,23.1,26.3,16.4,...,0.0,20.5,23.7,32.4,15.7,NE,19.550000,7.146719,11.278843,57.0
26,Matthew Stafford,13.6,17.3,13.8,27.4,25.6,9.3,27.4,0.0,26.8,...,23.2,20.9,30.9,12.8,26.7,LAR,19.461111,8.340133,9.620976,112.0
1,Baker Mayfield,22.6,19.9,17.7,18.9,26.7,19.6,11.1,4.1,0.0,...,11.1,19.2,12.7,17.4,13.2,TB,15.105556,7.139078,8.724068,144.0
15,Jared Goff,10.9,34.0,12.7,12.7,20.1,16.8,10.3,0.0,19.4,...,16.2,25.5,26.5,2.1,15.2,DET,16.505556,8.381806,8.119270,127.0
7,Caleb Williams,24.2,17.0,29.1,11.8,0.0,19.9,4.7,11.8,38.7,...,14.9,19.0,21.0,23.0,16.6,CHI,17.683333,9.116646,7.997486,86.0
36,Trevor Lawrence,10.3,19.2,7.8,11.7,26.2,19.2,17.6,0.0,21.2,...,19.4,44.3,31.2,23.1,23.3,JAX,18.783333,9.729352,7.960002,89.0
10,Dak Prescott,7.8,22.1,12.0,31.0,28.3,22.3,23.3,6.6,15.4,...,18.4,12.0,19.2,22.7,0.7,DAL,17.433333,9.144912,7.860051,92.0
2,Bo Nix,6.8,20.2,13.4,25.7,17.9,13.4,40.0,23.8,18.5,...,16.0,29.1,15.2,19.5,10.5,DEN,16.933333,9.163290,7.619307,120.0
8,Cam Ward,2.5,9.8,12.0,4.5,8.0,6.9,10.2,12.8,6.4,...,11.1,15.0,18.0,17.0,9.2,TEN,10.372222,5.835269,7.328843,200.0
0,Aaron Rodgers,25.7,10.4,11.7,12.8,0.0,17.5,22.6,16.8,12.1,...,21.5,17.0,15.5,7.3,17.8,PIT,12.622222,7.457768,6.978329,239.0
20,Josh Allen,38.8,11.8,23.0,24.9,19.4,15.4,0.0,23.2,28.8,...,37.8,24.5,6.9,23.2,0.0,BUF,20.250000,12.245011,6.818523,19.0
32,Sam Darnold,5.4,15.8,16.7,16.1,27.6,20.0,8.6,0.0,27.2,...,22.3,11.3,19.5,6.1,8.8,SEA,13.077778,8.398988,6.419947,192.0
5,Bryce Young,8.2,21.3,11.6,10.3,12.0,18.5,10.5,0.0,3.0,...,0.0,15.4,17.6,8.9,16.5,CAR,12.111111,8.451167,5.908698,209.0
6,C.J. Stroud,8.7,15.0,10.4,18.4,28.8,0.0,13.7,21.7,4.4,...,12.6,23.4,11.5,13.8,17.3,HOU,11.594444,8.555457,5.587675,174.0
14,Jacoby Brissett,0.0,0.2,0.0,0.0,0.0,20.7,19.8,0.0,24.8,...,19.0,20.6,10.6,16.5,15.6,ARI,12.633333,9.597610,5.427244,215.0
16,Jaxson Dart,0.0,-0.3,0.3,19.8,15.6,23.6,28.4,19.4,27.2,...,0.0,22.1,0.0,25.1,20.4,NYG,13.416667,11.597173,4.769985,93.0
25,Lamar Jackson,29.4,26.3,27.0,10.7,0.0,0.0,0.0,0.0,25.6,...,21.1,14.6,4.7,0.0,20.4,BAL,11.933333,10.792100,4.559112,35.0
38,Tyler Shough,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.3,9.2,...,21.3,18.1,17.1,21.9,21.8,NO,8.777778,9.302027,3.890733,153.0
4,Brock Purdy,16.8,0.0,0.0,17.7,0.0,0.0,0.0,0.0,0.0,...,0.0,26.2,30.9,36.9,5.2,SF,9.855556,12.355624,3.288826,109.0
18,Joe Flacco,12.2,8.8,3.7,1.3,0.0,18.8,26.0,24.3,30.7,...,0.0,0.0,0.2,1.2,0.2,CIN,8.161111,10.281058,3.272924,455.0
13,J.J. McCarthy,22.2,2.8,0.0,0.0,0.0,0.0,0.0,0.0,18.9,...,20.4,23.5,8.3,0.0,8.0,MIN,6.961111,8.875952,3.233613,269.0
17,Joe Burrow,8.8,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,23.4,5.5,29.0,20.4,21.1,CIN,7.466667,10.208820,3.015614,59.0
24,Kirk Cousins,0.0,0.0,1.2,0.0,0.0,0.0,0.0,7.1,0.0,...,2.5,26.9,17.6,9.1,9.2,ATL,5.755556,7.884700,3.009723,452.0
34,Shedeur Sanders,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.5,3.5,11.2,9.4,5.0,CLE,4.722222,8.375774,2.324588,251.0
11,Davis Mills,0.0,0.0,0.0,0.0,1.2,0.0,0.0,0.0,6.2,...,0.0,0.0,0.0,0.0,2.6,HOU,3.811111,7.790257,2.017085,308.0
30,Quinn Ewers,0.0,0.0,0.0,0.0,0.0,0.0,2.1,0.0,0.0,...,0.0,0.0,6.9,15.8,8.4,MIA,1.844444,4.277055,1.778055,520.0
37,Trey Lance,0.0,0.0,0.0,0.0,2.9,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.3,LAC,0.755556,2.032449,1.532749,305.0
22,Joshua Dobbs,0.0,0.0,0.0,-0.2,0.0,0.0,0.3,0.0,0.0,...,0.0,0.0,0.0,1.1,0.9,NE,0.116667,0.334752,1.436972,401.0
21,Josh Johnson,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.3,8.9,15.7,WAS,1.350000,4.151435,1.340788,498.0
31,Riley Leonard,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.0,...,10.3,0.0,0.0,-2.0,20.6,IND,1.611111,5.356347,1.240170,513.0
19,Joe Milton III,0.0,0.0,-0.4,0.0,0.0,0.0,0.0,6.3,0.0,...,0.0,0.0,-0.9,0.0,5.2,DAL,0.566667,1.908495,1.224225,551.0
9,Chris Oladokun,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,5.1,7.7,-1.7,KC,0.616667,2.187464,1.162342,285.0
35,Tanner McKee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.2,0.0,...,0.0,2.2,-0.2,0.0,11.9,PHI,0.772222,2.826722,1.126377,276.0
28,Mitchell Trubisky,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.9,0.0,...,0.0,0.0,0.0,0.0,28.9,BUF,1.733333,6.787098,1.052986,397.0
3,Brandon Allen,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.9,TEN,0.050000,0.212132,0.971825,496.0
33,Shane Buechele,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.9,KC,0.216667,0.919239,0.971825,304.0
23,Kenny Pickett,0.0,0.0,0.0,0.0,0.0,0.0,-1.7,0.0,0.0,...,8.5,1.3,0.0,0.6,-1.0,LV,0.427778,2.098965,0.840306,295.0
39,Zach Wilson,1.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.2,0.0,0.0,0.0,0.0,MIA,0.077778,0.382800,0.837737,311.0
27,Max Brosmer,0.0,0.0,1.2,0.0,-0.1,0.0,0.0,0.5,0.0,...,0.0,0.0,1.8,3.6,0.3,MIN,0.233333,1.251352,0.768815,623.0
29,Nick Mullens,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-0.2,0.0,0.0,0.4,JAX,-0.005556,0.130484,-0.175547,393.0

In [43]:
rb.sort_values(by="ProxySharpe", ascending=False)

,NAME,FPTS_WK1,FPTS_WK2,FPTS_WK3,FPTS_WK4,FPTS_WK5,FPTS_WK6,FPTS_WK7,FPTS_WK8,FPTS_WK9,...,FPTS_WK14,FPTS_WK15,FPTS_WK16,FPTS_WK17,FPTS_WK18,TEAM,Average,StdDev,ProxySharpe,ADP
11,Christian McCaffrey,23.2,22.7,24.0,26.1,27.9,24.1,39.1,9.8,34.3,...,0.0,15.7,32.6,28.1,11.7,SF,23.144444,9.850185,9.687837,5.0
36,Kyren Williams,13.9,10.0,19.2,10.4,31.1,16.7,8.5,0.0,17.4,...,17.7,21.8,11.5,16.0,11.1,LAR,14.627778,6.965529,8.658621,20.0
9,Chase Brown,13.1,8.5,6.0,10.1,11.8,8.9,12.0,25.5,19.2,...,18.5,16.0,32.9,29.1,19.0,CIN,15.700000,8.132867,7.959402,16.0
46,Travis Etienne Jr.,18.6,16.9,11.6,19.5,8.8,9.5,6.5,0.0,16.5,...,21.2,31.5,16.6,11.2,4.8,JAX,14.105556,7.601275,7.651177,34.0
3,Bijan Robinson,24.4,19.8,16.1,28.1,0.0,35.8,21.2,5.8,17.6,...,9.4,29.5,29.8,39.9,7.3,ATL,20.600000,11.201576,7.582503,2.0
25,Jaylen Warren,13.9,17.4,13.1,0.0,0.0,8.3,19.8,9.3,16.9,...,15.2,7.8,29.1,6.4,14.9,PIT,12.061111,6.861241,7.247848,60.0
45,Tony Pollard,7.9,9.2,13.9,10.6,14.8,6.7,12.1,6.3,7.8,...,28.1,18.2,10.2,11.5,9.5,TEN,10.322222,6.029687,7.058345,70.0
23,James Cook III,21.2,26.5,20.8,22.5,4.9,8.7,0.0,33.6,13.5,...,11.1,31.1,26.4,8.7,1.5,BUF,16.788889,9.861266,7.019622,7.0
13,D'Andre Swift,9.5,13.9,10.8,16.0,0.0,25.5,20.8,15.1,0.0,...,11.2,22.6,9.0,21.9,5.8,CHI,12.700000,7.785809,6.725498,46.0
31,Kenneth Walker,5.4,18.8,18.0,12.0,9.6,4.7,6.6,0.0,8.1,...,3.8,2.9,25.4,7.7,17.3,SEA,10.661111,6.870751,6.397683,18.0
27,Jonathan Taylor,12.8,29.5,32.8,14.6,31.6,23.7,34.2,37.4,7.7,...,11.4,13.1,16.9,17.4,5.9,IND,20.127778,13.073584,6.347835,4.0
0,Ashton Jeanty,12.0,7.4,6.3,33.5,15.9,16.6,4.4,0.0,19.9,...,5.8,8.2,31.8,9.3,12.4,LV,13.616667,9.085428,6.179451,15.0
16,Derrick Henry,29.2,2.3,10.7,7.8,9.3,14.0,0.0,19.1,13.1,...,11.2,10.0,22.8,45.6,12.6,BAL,15.527778,10.449194,6.127044,10.0
22,Jahmyr Gibbs,15.0,19.4,26.9,17.7,16.7,7.5,36.8,0.0,5.8,...,37.0,9.8,22.8,6.4,20.3,DET,20.383333,14.074769,5.971156,1.0
38,RJ Harvey,7.9,3.4,4.6,19.8,6.0,6.5,7.2,24.1,16.6,...,22.0,10.5,22.1,18.6,4.3,DEN,11.477778,7.960606,5.944785,67.0
39,Rachaad White,2.6,14.6,2.4,8.6,23.1,17.6,8.4,8.1,0.0,...,6.5,3.6,8.0,3.7,6.1,TB,7.944444,5.690469,5.756254,118.0
55,Zach Charbonnet,10.7,1.0,0.0,12.4,11.8,4.7,19.5,0.0,5.6,...,8.6,3.1,17.4,26.2,18.7,SEA,10.077778,7.282578,5.705636,122.0
15,David Montgomery,8.3,13.1,29.4,1.2,18.2,8.1,5.9,0.0,11.0,...,14.3,9.2,1.4,6.0,6.5,DET,9.272222,6.917991,5.526222,50.0
32,Kenny Gainwell,5.3,6.6,9.6,31.4,0.0,9.6,3.5,3.5,7.4,...,16.2,19.6,23.8,6.8,21.4,PIT,12.294444,9.601377,5.279586,91.0
35,Kyle Monangai,2.1,4.6,3.0,1.8,0.0,5.4,17.4,2.4,22.8,...,8.7,3.3,12.3,7.7,5.9,CHI,8.150000,6.422685,5.231972,82.0
50,Tyler Allgeier,2.4,15.0,1.4,11.1,0.0,10.8,1.6,9.4,0.6,...,8.7,1.8,8.3,2.3,2.9,ATL,6.833333,5.463139,5.157210,110.0
28,Jordan Mason,8.5,5.8,23.6,10.2,12.6,0.0,11.7,1.6,4.7,...,11.2,2.9,2.1,0.0,9.4,MIN,7.161111,5.785798,5.103189,96.0
42,Rico Dowdle,3.6,2.9,10.8,4.0,32.4,33.9,10.6,5.4,28.1,...,0.0,12.4,8.3,9.3,3.0,CAR,12.016667,9.970855,4.969081,71.0
54,Woody Marks,0.3,6.1,4.6,27.9,2.4,0.0,12.5,15.1,2.7,...,15.6,10.8,0.0,8.5,6.8,HOU,8.394444,7.122415,4.859473,119.0
47,TreVeyon Henderson,11.1,6.0,7.7,12.6,4.7,4.6,0.5,5.5,12.7,...,0.0,30.1,2.2,8.2,17.3,NE,11.455556,9.739563,4.849547,51.0
51,Tyler Badie,3.6,4.2,0.0,2.1,2.6,0.0,3.9,0.6,2.6,...,3.1,1.1,1.2,0.0,4.6,DEN,1.966667,1.747940,4.639046,287.0
53,Tyrone Tracy Jr.,5.5,9.1,5.6,0.0,0.0,0.6,10.6,7.3,6.7,...,0.0,24.7,9.8,6.7,27.9,NYG,8.933333,8.076036,4.560787,126.0
12,Chuba Hubbard,17.9,18.7,9.6,9.9,0.0,0.0,7.5,9.4,1.7,...,0.0,4.8,4.4,2.8,3.7,CAR,6.966667,6.434375,4.464195,84.0
6,Brian Robinson,4.7,2.9,2.2,2.1,1.2,3.8,3.6,0.0,11.3,...,0.0,2.1,2.0,3.8,0.9,SF,3.472222,3.225415,4.438604,121.0
4,Blake Corum,2.6,10.4,5.3,3.6,1.3,2.3,5.3,0.0,5.8,...,26.1,13.1,13.1,1.8,7.9,LAR,6.788889,6.522981,4.291183,83.0
21,Jacory Croskey-Merritt,14.2,1.7,10.1,7.7,27.0,5.8,4.2,2.5,5.1,...,3.2,15.6,8.5,22.5,2.9,WAS,7.794444,7.502194,4.283723,98.0
37,Michael Carter,0.0,0.0,0.0,0.1,18.3,8.4,5.6,0.0,0.0,...,5.1,13.4,6.5,6.3,6.9,ARI,5.500000,5.400654,4.198951,347.0
49,Tyjae Spears,0.0,0.0,0.0,0.0,1.4,9.0,7.0,17.2,9.2,...,6.7,5.6,21.5,1.1,9.7,TEN,6.205556,6.118677,4.181650,132.0
2,Bhayshul Tuten,1.1,15.4,8.1,3.2,2.1,4.8,2.2,0.0,9.6,...,-1.5,9.3,0.0,0.0,8.3,JAX,4.922222,5.005004,4.054910,52.0
41,Rhamondre Stevenson,4.7,21.2,4.6,5.1,14.7,1.8,16.8,5.9,0.0,...,0.0,10.7,17.8,27.2,35.3,NE,9.933333,10.350504,3.956926,62.0
17,Devin Singletary,0.9,1.0,1.1,2.8,3.4,1.0,0.2,3.8,7.1,...,0.0,2.4,5.6,17.0,10.6,NYG,6.044444,6.321134,3.942629,320.0
10,Chris Rodriguez Jr.,0.0,0.0,3.9,5.9,0.7,0.0,7.2,0.2,12.5,...,5.2,0.0,13.9,0.0,15.3,WAS,5.111111,5.383951,3.914161,139.0
7,Bucky Irving,14.5,18.1,13.9,25.5,0.0,0.0,0.0,0.0,0.0,...,16.1,8.1,7.1,8.3,10.8,TB,7.694444,8.173161,3.881608,39.0
43,Samaje Perine,2.6,0.0,0.1,0.4,4.9,5.2,3.1,17.0,0.5,...,4.8,5.3,12.1,8.3,8.2,CIN,4.327778,4.743640,3.761644,354.0
30,Keaton Mitchell,0.0,0.0,0.0,0.0,2.3,0.0,0.0,4.3,2.8,...,7.6,6.6,1.3,5.8,0.2,BAL,3.077778,3.376311,3.758541,152.0
5,Brashard Smith,0.0,0.2,1.3,6.6,6.6,5.1,13.1,0.8,0.7,...,0.7,0.1,1.4,9.5,7.8,KC,3.516667,3.984861,3.638668,282.0
18,Dylan Sampson,17.3,10.9,0.2,0.0,1.2,4.4,2.7,7.9,0.0,...,9.8,0.0,0.0,5.7,6.4,CLE,4.877778,5.541348,3.629368,146.0
34,Kimani Vidal,0.0,0.0,0.0,0.0,2.9,22.8,7.5,19.7,3.0,...,11.4,5.8,1.1,0.0,2.0,LAC,6.550000,8.166377,3.307016,170.0
19,Emanuel Wilson,0.4,0.0,2.5,11.1,0.0,1.7,2.5,11.7,2.7,...,1.0,0.3,8.2,3.4,5.8,GB,5.250000,6.858764,3.156006,212.0
44,Tank Bigsby,1.2,0.0,0.0,0.0,0.0,0.0,2.0,10.4,0.0,...,0.4,5.7,9.7,1.9,17.6,PHI,2.988889,4.884536,2.522963,158.0
52,Tyler Goodson,0.0,0.0,0.6,1.0,0.0,0.0,0.0,0.2,1.8,...,0.0,0.0,0.9,0.0,0.3,IND,0.288889,0.496919,2.397011,332.0
26,Jaylen Wright,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.8,0.0,...,16.7,2.1,12.3,5.6,4.0,MIA,2.677778,4.683708,2.357269,213.0
40,Ray Davis,1.1,2.4,0.0,0.3,0.1,9.9,0.0,1.6,0.0,...,0.0,2.3,5.4,2.6,25.4,BUF,3.227778,6.162296,2.159661,182.0
20,Hassan Haskins,0.0,0.0,0.0,0.0,2.5,3.3,2.5,0.0,0.0,...,0.0,0.0,1.4,0.0,0.3,LAC,0.555556,1.081514,2.117969,353.0
1,Audric Estimé,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.1,8.0,6.6,16.8,15.6,NO,2.672222,5.454820,2.019838,299.0
56,Zamir White,0.8,3.3,3.3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.2,2.0,LV,0.533333,1.120399,1.962684,310.0
14,Dameon Pierce,0.5,0.0,0.0,0.0,2.1,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,KC,0.200000,0.539062,1.529732,345.0
24,Jaydon Blue,0.0,0.0,0.0,0.0,0.7,0.0,4.4,2.9,0.0,...,0.0,0.0,0.0,0.0,12.4,DAL,1.133333,3.057296,1.528427,206.0
29,Julius Chestnut,0.2,0.0,2.6,0.0,0.3,0.0,0.0,0.5,0.0,...,0.0,0.0,0.1,0.0,0.0,TEN,0.222222,0.611224,1.499034,335.0
48,Ty Chandler,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.4,6.4,MIN,0.488889,1.579609,1.276101,350.0
8,Cam Akers,0.0,0.0,1.9,0.0,5.3,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,SEA,0.400000,1.302035,1.266665,337.0
33,Khalil Herbert,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.5,0.0,0.5,5.6,NYJ,0.366667,1.315965,1.148819,338.0

In [44]:
wr.sort_values(by="ProxySharpe", ascending=False)

,NAME,FPTS_WK1,FPTS_WK2,FPTS_WK3,FPTS_WK4,FPTS_WK5,FPTS_WK6,FPTS_WK7,FPTS_WK8,FPTS_WK9,...,FPTS_WK14,FPTS_WK15,FPTS_WK16,FPTS_WK17,FPTS_WK18,TEAM,Average,StdDev,ProxySharpe,ADP
26,Jaxon Smith-Njigba,19.4,18.3,20.6,13.0,27.2,30.2,26.3,0.0,22.0,...,28.1,18.3,23.6,16.2,14.4,SEA,19.994444,8.807715,9.359885,8.0
20,Jakobi Meyers,17.7,12.8,9.3,7.0,7.2,7.9,0.0,0.0,6.3,...,14.8,12.1,8.6,7.9,9.4,JAX,9.766667,5.416858,7.434014,95.0
31,Justin Jefferson,14.8,11.1,12.5,22.6,19.3,0.0,12.9,14.4,16.7,...,3.1,4.2,14.5,7.0,18.4,MIN,11.194444,6.275487,7.354948,17.0
43,Puka Nacua,23.1,27.6,22.8,36.0,24.5,4.8,0.0,0.0,22.8,...,35.7,27.9,46.5,15.7,26.0,LAR,20.833333,12.223074,7.027531,6.0
51,Zay Flowers,28.1,14.9,3.3,14.4,12.2,8.6,0.0,14.1,11.4,...,20.6,15.8,21.2,13.0,29.8,BAL,13.483333,8.063079,6.894787,43.0
45,Stefon Diggs,11.7,7.2,5.3,16.1,24.6,5.8,13.9,10.4,12.8,...,0.0,5.6,22.8,22.1,7.3,NE,11.683333,7.222941,6.669252,113.0
16,George Pickens,6.0,17.8,17.8,33.4,13.7,31.8,12.2,14.8,13.9,...,8.7,6.3,26.0,11.8,1.9,DAL,16.216667,10.199784,6.555338,29.0
1,Amon-Ra St. Brown,8.5,39.2,20.7,26.0,18.0,13.7,20.6,0.0,18.7,...,15.2,41.4,9.4,14.8,24.9,DET,18.000000,11.515258,6.445005,11.0
48,Tetairoa McMillan,11.8,16.0,7.8,10.2,13.3,17.9,6.3,16.9,8.6,...,0.0,4.5,19.3,0.0,10.5,CAR,11.661111,7.600088,6.326241,38.0
7,Courtland Sutton,18.1,0.0,23.8,19.1,17.9,2.7,16.7,10.7,10.0,...,12.2,24.3,20.6,8.0,1.5,DEN,12.116667,8.008249,6.238354,75.0
18,Ja'Marr Chase,4.6,36.5,8.9,7.3,29.0,25.1,38.1,21.1,17.1,...,10.2,23.2,19.9,25.0,23.6,CIN,17.422222,11.537130,6.226303,3.0
30,Josh Downs,3.2,11.1,5.4,6.4,11.4,16.2,0.0,12.9,15.7,...,6.3,10.3,11.8,5.4,9.6,IND,7.577778,5.048303,6.189007,108.0
38,Michael Pittman Jr.,20.0,8.0,19.3,15.1,14.9,4.0,20.8,23.5,20.5,...,16.9,5.6,7.2,3.6,3.1,IND,11.244444,7.788923,5.952303,106.0
33,Keenan Allen,19.8,17.1,19.5,8.7,10.8,6.7,28.9,8.4,6.1,...,5.2,8.6,9.4,2.7,10.6,LAC,10.150000,7.071920,5.917703,190.0
25,Jauan Jennings,3.6,19.9,0.0,6.4,0.0,1.7,7.1,8.5,14.1,...,0.0,18.7,18.1,12.2,7.5,SF,9.627778,6.817694,5.822547,148.0
14,Elic Ayomanor,3.3,15.6,13.8,6.4,3.8,5.7,4.9,9.2,7.6,...,8.4,2.7,8.8,13.7,8.0,TEN,6.472222,4.626116,5.768480,352.0
11,DeVonta Smith,4.6,9.3,20.0,4.9,19.4,8.9,33.3,14.4,0.0,...,7.7,7.0,16.2,4.5,8.2,PHI,11.211111,8.066626,5.730351,42.0
6,Cooper Kupp,3.5,16.0,5.1,6.6,11.9,12.0,2.2,0.0,0.0,...,11.5,9.6,6.9,0.0,4.9,SEA,6.372222,4.591399,5.722296,225.0
12,Deebo Samuel Sr.,22.6,17.4,4.9,20.1,23.6,5.4,0.0,4.2,9.4,...,6.7,7.3,6.5,11.3,4.1,WAS,10.455556,7.549696,5.710079,143.0
24,Jameson Williams,6.6,18.8,6.3,5.7,2.0,18.6,0.0,0.0,16.6,...,17.3,26.4,12.0,5.7,13.4,DET,12.216667,9.214646,5.466364,55.0
3,CeeDee Lamb,18.0,20.2,0.0,0.0,0.0,0.0,22.0,14.6,15.5,...,18.1,17.1,11.1,9.6,1.4,DAL,11.161111,8.718415,5.278304,13.0
46,Tee Higgins,6.3,14.6,2.5,6.2,11.2,11.2,21.6,11.4,33.1,...,27.2,0.0,14.3,9.9,18.7,CIN,11.755556,9.218921,5.257600,36.0
50,Tre' Harris,2.1,5.4,0.0,0.0,0.0,6.7,4.3,8.8,3.8,...,3.1,7.9,9.4,2.5,4.8,LAC,3.855556,3.044034,5.222301,189.0
2,Brian Thomas Jr.,9.0,8.9,7.5,10.6,12.0,23.0,6.1,0.0,8.5,...,11.7,17.1,3.8,7.9,7.9,JAX,7.711111,6.100038,5.212054,79.0
15,Emeka Egbuka,23.6,12.9,14.5,20.1,31.3,4.4,9.8,6.5,0.0,...,3.5,10.4,5.0,5.0,1.8,TB,10.872222,8.608669,5.207230,53.0
28,Jerry Jeudy,11.6,9.1,2.7,7.8,3.5,9.3,3.7,0.0,0.0,...,16.6,4.2,4.2,10.4,4.2,CLE,6.705556,5.330431,5.186769,179.0
41,Parker Washington,0.0,12.6,7.4,0.0,9.6,4.9,10.2,0.0,17.0,...,0.0,8.3,26.5,19.0,19.7,JAX,9.600000,7.978869,4.960830,68.0
29,Jordan Addison,0.0,0.0,0.0,15.4,15.1,0.0,21.8,11.6,8.4,...,10.2,8.6,4.6,12.5,1.8,MIN,7.505556,6.446109,4.800756,101.0
0,Alec Pierce,4.6,10.8,10.7,0.0,0.0,6.8,14.8,8.9,17.5,...,13.0,2.6,24.6,0.0,29.2,IND,10.183333,8.872777,4.732110,94.0
9,Darnell Mooney,0.0,4.0,8.4,2.5,0.0,0.0,9.8,2.1,2.5,...,1.6,6.5,4.4,5.5,5.0,ATL,4.572222,4.059094,4.644326,223.0
8,DJ Moore,8.6,9.6,12.8,7.8,0.0,8.2,8.2,11.6,23.0,...,0.6,22.9,21.9,0.0,2.1,CHI,9.361111,8.400080,4.594819,54.0
39,Michael Wilson,0.0,8.1,0.0,4.5,3.6,8.4,7.0,0.0,9.1,...,37.2,16.4,13.2,19.9,20.9,ARI,12.088889,10.917654,4.565428,81.0
49,Tre Tucker,13.4,4.9,40.9,4.2,11.1,12.0,8.3,0.0,6.8,...,4.4,0.0,9.4,9.9,5.4,LV,8.983333,8.956184,4.135604,183.0
4,Chimere Dike,0.0,0.0,3.5,0.0,3.7,2.8,16.9,16.4,1.5,...,13.4,5.0,13.0,10.2,5.7,TEN,6.161111,6.259782,4.058115,361.0
42,Pat Bryant,0.0,3.8,0.0,0.0,0.0,4.2,1.6,12.0,4.0,...,7.2,0.0,9.2,0.0,7.1,DEN,4.155556,4.371461,3.919466,208.0
10,DeMario Douglas,8.2,0.0,2.7,0.0,3.7,16.1,4.7,5.7,20.0,...,0.0,0.0,0.0,2.0,4.9,NE,5.105556,5.445394,3.865789,390.0
32,Kayshon Boutte,16.3,8.6,4.8,2.8,7.3,26.3,13.5,16.5,0.0,...,0.0,4.0,2.6,0.0,4.4,NE,6.894444,7.479499,3.800592,169.0
47,Terry McLaurin,4.7,9.8,10.4,0.0,0.0,0.0,0.0,14.4,0.0,...,7.1,15.9,8.3,11.3,9.7,WAS,6.344444,6.918706,3.780882,56.0
13,Drake London,13.5,5.9,10.5,25.0,0.0,31.8,8.2,0.0,38.8,...,0.0,0.0,5.7,0.0,17.8,ATL,11.138889,12.378308,3.710266,21.0
34,Keon Coleman,25.2,5.6,5.0,7.5,10.3,4.1,0.0,6.0,3.7,...,3.6,0.0,0.0,0.0,8.9,BUF,5.688889,6.389503,3.671004,240.0
35,Luther Burden III,0.0,0.0,19.8,0.0,0.0,9.1,3.1,0.9,0.0,...,11.0,14.4,0.0,27.8,7.5,CHI,6.894444,7.767918,3.659478,41.0
44,Ryan Flournoy,0.0,0.0,4.1,4.6,18.4,6.3,0.0,1.7,9.2,...,26.5,8.0,9.8,0.0,11.8,DAL,6.333333,7.178727,3.637553,217.0
37,Matthew Golden,3.6,0.0,10.1,11.3,0.0,13.2,7.7,3.4,2.9,...,0.0,8.5,0.0,2.2,1.8,GB,3.783333,4.408581,3.538345,150.0
23,Jalen Nailor,3.8,6.1,6.7,9.2,7.2,0.0,5.7,0.0,2.6,...,6.0,19.5,0.0,0.0,7.9,MIN,5.594444,6.606100,3.491695,195.0
36,Marvin Mims Jr.,2.2,10.4,0.0,20.5,3.9,4.8,15.8,1.8,0.0,...,1.7,7.7,5.9,4.0,3.0,DEN,4.744444,5.713166,3.423994,392.0
21,Jalen Coker,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.6,1.9,...,0.0,14.0,7.7,3.6,16.7,CAR,5.022222,6.101837,3.393593,141.0
17,Isaac TeSlaa,8.3,3.9,0.0,0.0,8.2,0.0,0.0,0.0,0.0,...,10.0,0.0,15.2,13.9,2.8,DET,4.216667,5.423505,3.205632,214.0
19,Jahan Dotson,8.9,0.0,0.0,0.0,3.4,2.7,0.0,11.0,0.0,...,1.3,0.0,4.3,0.0,7.0,PHI,2.616667,3.510698,3.073119,383.0
27,Jaylin Noel,0.0,0.0,0.0,0.0,9.8,0.0,11.7,11.3,0.0,...,3.3,0.0,0.0,14.6,2.3,HOU,3.588889,4.987147,2.967101,386.0
40,Mike Evans,10.1,10.6,13.3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,19.2,14.1,12.1,5.4,TB,4.711111,6.574361,2.954570,61.0
5,Chris Godwin Jr.,0.0,0.0,0.0,5.6,5.6,0.0,0.0,0.0,0.0,...,10.5,14.0,8.0,23.8,1.8,TB,4.611111,6.619836,2.871990,88.0
22,Jalen McMillan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,5.8,3.6,18.4,2.1,TB,1.661111,4.471497,1.531688,172.0

In [45]:
te.sort_values(by="ProxySharpe", ascending=False)

,NAME,FPTS_WK1,FPTS_WK2,FPTS_WK3,FPTS_WK4,FPTS_WK5,FPTS_WK6,FPTS_WK7,FPTS_WK8,FPTS_WK9,...,FPTS_WK14,FPTS_WK15,FPTS_WK16,FPTS_WK17,FPTS_WK18,TEAM,Average,StdDev,ProxySharpe,ADP
62,Tyler Warren,14.9,11.9,6.8,18.3,14.4,18.3,16.9,9.3,7.6,...,3.7,4.9,6.0,9.3,7.6,IND,10.472222,5.406402,7.986472,58.0
59,Trey McBride,12.1,13.8,15.3,12.2,9.1,21.2,29.4,0.0,16.5,...,10.8,37.4,6.7,23.6,13.5,ARI,17.550000,9.223005,7.845654,25.0
37,Juwan Johnson,15.6,15.9,11.1,5.8,3.7,1.5,12.9,10.3,12.1,...,7.8,7.0,16.9,13.5,7.1,NO,9.994444,5.303658,7.769760,124.0
14,Dalton Schultz,5.8,5.9,8.9,8.0,11.0,0.0,18.8,4.4,13.7,...,5.2,21.6,14.5,4.9,11.3,HOU,9.872222,5.999981,6.784057,135.0
58,Travis Kelce,12.7,10.1,6.6,9.8,19.1,13.8,8.4,21.9,12.6,...,1.8,14.0,1.6,8.6,4.2,KC,10.733333,6.766787,6.539982,103.0
8,Chig Okonkwo,4.9,7.5,11.6,1.4,8.8,10.6,0.0,9.3,3.0,...,4.0,7.3,16.4,14.5,2.2,TEN,6.888889,4.676335,6.073906,155.0
28,Jake Ferguson,7.3,16.8,21.2,17.0,23.9,12.3,21.9,0.0,8.0,...,10.8,3.6,4.9,7.6,1.5,DAL,10.450000,7.355610,5.857632,111.0
19,Evan Engram,5.1,2.2,0.0,6.9,13.3,9.9,9.2,7.6,0.0,...,2.8,2.2,5.6,6.1,7.5,DEN,5.711111,4.221080,5.578552,355.0
25,Hunter Henry,10.6,1.9,29.0,11.9,6.6,5.7,7.3,7.7,9.1,...,0.0,2.8,15.5,13.9,10.6,NE,9.933333,7.480956,5.474726,131.0
10,Cole Kmet,4.1,4.9,8.0,7.6,0.0,1.0,2.6,0.0,2.0,...,6.2,4.8,3.4,3.6,5.6,CHI,4.372222,3.434737,5.248476,505.0
0,AJ Barner,1.2,10.8,3.3,12.2,24.3,10.1,1.9,0.0,11.5,...,5.7,5.7,15.0,13.3,3.4,SEA,8.183333,6.621822,5.095387,164.0
34,Jonnu Smith,12.5,6.7,5.3,2.6,0.0,5.8,11.8,3.7,5.5,...,0.0,10.6,2.8,7.7,1.4,PIT,4.733333,3.978915,4.904863,654.0
38,Kyle Pitts Sr.,12.9,7.7,7.9,18.0,0.0,4.8,13.2,14.9,7.8,...,15.0,45.6,18.7,3.6,11.8,ATL,11.711111,10.076991,4.791723,77.0
5,Cade Otton,0.0,5.5,0.0,3.9,12.1,10.1,13.5,8.0,0.0,...,4.9,0.0,3.5,7.3,22.4,TB,6.788889,6.260698,4.470956,188.0
16,Dawson Knox,4.0,3.9,0.0,0.0,3.5,8.9,0.0,2.5,4.0,...,17.3,18.7,2.0,8.0,10.4,BUF,5.761111,5.336571,4.451111,342.0
4,Brenton Strange,9.9,4.7,12.1,10.5,3.2,0.0,0.0,0.0,0.0,...,5.7,3.6,14.9,8.4,17.2,JAX,6.555556,6.107105,4.425869,130.0
42,Mark Andrews,1.5,1.4,27.1,10.0,4.2,6.6,0.0,6.4,16.6,...,1.9,3.8,4.4,6.8,3.4,BAL,7.277778,6.829482,4.393751,114.0
11,Colston Loveland,3.2,0.0,4.1,0.0,0.0,3.1,5.4,6.8,29.8,...,12.9,10.1,6.0,21.4,25.1,CHI,9.172222,8.653650,4.370184,44.0
32,Jeremy Ruckert,3.6,7.5,0.0,3.3,6.8,0.0,0.0,3.4,0.0,...,3.9,3.3,3.4,1.2,0.0,NYJ,2.605556,2.493868,4.307758,470.0
3,Austin Hooper,2.0,6.8,4.8,3.4,0.0,1.5,9.1,5.8,3.0,...,0.0,0.0,5.4,9.1,1.5,NE,3.294444,3.244991,4.185941,677.0
48,Noah Gray,1.3,1.1,4.7,1.1,0.0,4.5,3.8,4.3,0.0,...,2.4,0.0,0.0,1.2,6.0,KC,2.155556,2.136578,4.159727,479.0
41,Luke Musgrave,1.4,5.2,0.0,1.6,0.0,1.7,0.0,1.5,6.4,...,4.2,9.2,6.8,0.0,0.0,GB,2.733333,2.811531,4.008429,449.0
50,Pat Freiermuth,5.8,6.1,1.6,0.0,0.0,2.1,28.1,4.3,11.7,...,2.9,7.5,6.0,9.3,8.1,PIT,6.311111,6.532893,3.983132,415.0
9,Colby Parkinson,-0.6,0.0,0.0,3.7,0.0,0.0,7.7,0.0,3.0,...,12.2,24.5,4.1,11.3,19.6,LAR,7.211111,7.494931,3.966971,180.0
49,Oronde Gadsden,0.0,0.0,9.6,3.6,2.4,11.8,29.4,18.7,11.8,...,1.7,10.1,1.7,12.2,4.3,LAC,7.300000,7.626193,3.946749,125.0
13,Dalton Kincaid,14.8,7.7,17.6,9.8,16.8,0.0,0.0,3.3,22.1,...,14.1,6.4,0.0,0.0,7.8,BUF,7.005556,7.337933,3.936346,100.0
21,George Kittle,12.5,0.0,0.0,0.0,0.0,0.0,0.0,14.3,6.9,...,0.0,22.8,24.5,0.0,7.9,SF,8.972222,9.714804,3.807943,97.0
47,Noah Fant,12.6,5.8,5.6,0.0,0.0,6.7,14.4,7.1,10.8,...,2.5,0.0,0.0,0.0,-0.5,CIN,4.155556,4.774839,3.588350,556.0
1,Adam Trautman,1.5,10.0,0.0,5.2,2.1,0.0,0.0,0.0,4.5,...,3.7,0.0,3.4,4.4,0.0,DEN,2.527778,2.945746,3.538084,560.0
45,Mitchell Evans,0.0,1.9,1.9,11.3,7.4,3.1,4.4,0.0,0.0,...,0.0,0.0,5.3,1.6,1.5,CAR,2.677778,3.167028,3.486158,757.0
27,Isaiah Likely,0.0,0.0,0.0,0.0,2.2,2.6,0.0,2.8,9.0,...,12.5,0.0,0.0,5.7,5.2,BAL,3.427778,4.136751,3.416471,115.0
57,Tommy Tremble,1.2,5.0,3.6,15.2,1.7,7.9,1.0,1.4,0.0,...,0.0,3.3,1.6,1.6,12.8,CAR,3.550000,4.433197,3.301686,434.0
56,Tanner Hudson,0.0,0.0,0.0,0.0,0.0,11.0,0.0,1.9,6.2,...,2.1,4.6,1.4,5.1,0.0,CIN,2.655556,3.350719,3.267697,720.0
29,Jake Tonges,10.5,7.1,4.1,14.8,17.1,11.8,0.0,7.2,0.0,...,0.0,0.0,1.7,19.0,0.0,SF,5.183333,6.687499,3.195728,222.0
23,Greg Dulcich,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.9,...,7.1,6.6,5.6,16.1,6.1,MIA,3.488889,4.502926,3.194602,272.0
43,Michael Mayer,7.8,2.9,0.0,0.0,0.0,16.0,2.0,0.0,5.6,...,0.0,0.0,2.0,17.9,7.7,LV,4.100000,5.385274,3.139066,431.0
44,Mike Gesicki,2.4,4.8,1.6,1.8,3.5,0.0,0.0,0.0,0.0,...,20.6,2.1,12.5,6.7,3.3,CIN,3.927778,5.321522,3.043235,491.0
61,Tyler Higbee,0.0,7.7,0.0,4.5,0.0,14.0,4.9,0.0,10.3,...,0.0,0.0,0.0,0.0,20.1,LAR,3.950000,5.837934,2.789731,671.0
17,Drew Sample,0.0,1.7,10.0,0.0,0.9,0.8,0.0,0.0,0.0,...,0.0,3.2,5.1,1.8,4.7,CIN,1.772222,2.630993,2.777301,552.0
6,Charlie Kolar,0.0,0.0,4.2,0.0,2.0,0.0,0.0,8.0,10.3,...,2.9,0.0,2.8,0.0,0.0,BAL,2.011111,3.003506,2.760782,450.0
35,Josh Oliver,1.5,0.0,8.2,0.0,11.5,0.0,1.9,0.0,0.0,...,16.4,2.8,3.9,1.8,4.9,MIN,3.055556,4.595423,2.741506,493.0
15,Daniel Bellinger,2.4,0.0,1.6,2.3,9.2,0.0,17.8,3.1,0.0,...,0.0,6.5,0.0,3.1,11.8,NYG,3.311111,4.980537,2.741082,435.0
33,John Bates,0.0,0.0,0.0,0.0,1.9,0.0,1.5,3.2,4.0,...,0.0,2.9,0.0,0.0,9.3,WAS,1.516667,2.383337,2.623791,537.0
26,Ian Thomas,0.0,0.0,0.0,0.0,5.0,1.4,0.0,0.0,1.9,...,3.7,0.0,0.0,0.0,0.0,LV,1.355556,2.185304,2.557584,684.0
46,Mo Alie-Cox,3.0,1.8,0.0,0.0,0.0,2.6,1.6,0.0,0.0,...,0.0,0.0,3.6,11.0,5.2,IND,1.705556,2.805556,2.506521,644.0
40,Luke Farrell,1.4,9.5,0.0,2.0,1.8,0.0,2.1,0.0,1.9,...,0.0,0.0,0.0,0.0,0.0,SF,1.638889,2.980947,2.266834,467.0
12,Connor Heyward,0.0,1.6,0.0,0.2,0.0,8.2,0.0,0.0,0.4,...,0.2,6.4,0.0,2.6,7.5,PIT,1.522222,2.790647,2.249042,302.0
22,Grant Calcaterra,0.0,1.6,0.0,2.6,3.8,0.0,0.0,0.0,0.0,...,0.0,1.4,0.0,1.3,10.1,PHI,1.255556,2.476768,2.090139,516.0
18,Durham Smythe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.2,0.0,0.0,2.1,0.0,CHI,0.361111,0.715492,2.080946,610.0
52,Quintin Morris,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,1.5,0.0,7.5,JAX,0.972222,1.994936,2.009375,614.0
60,Tyler Conklin,7.2,0.0,0.0,1.3,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.6,LAC,0.961111,2.019068,1.962670,574.0
7,Charlie Woerner,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.2,1.3,0.0,0.0,ATL,0.711111,1.495046,1.961134,548.0
2,Anthony Firkser,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.7,0.0,8.0,0.0,2.2,DET,0.738889,1.938204,1.571825,778.0
39,Kylen Granson,1.1,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,7.0,PHI,0.611111,1.675038,1.504250,590.0
20,Feleipe Franks,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,ATL,0.022222,0.064676,1.416667,600.0
24,Harrison Bryant,0.0,0.0,0.0,0.0,1.5,0.0,0.0,0.0,1.2,...,0.0,0.0,0.0,0.0,0.0,HOU,0.150000,0.439585,1.406930,611.0
30,James Mitchell,0.0,0.0,0.0,3.7,2.1,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,CAR,0.322222,0.977124,1.359660,567.0
55,Stone Smartt,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.4,3.8,0.0,NYJ,0.677778,2.124522,1.315378,530.0
36,Josiah Deguara,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,9.5,ARI,0.616667,2.248725,1.130677,606.0
53,Robert Tonyan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,KC,0.061111,0.259272,0.971825,549.0
54,Shane Zylstra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,5.0,0.0,0.0,DET,0.277778,1.178511,0.971825,489.0
31,Jared Wiley,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,KC,0.077778,0.329983,0.971825,772.0
51,Pharaoh Brown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.1,0.0,0.0,0.0,ARI,0.116667,0.494975,0.971825,753.0